[package]
name = "robine-api-http"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
actix-web.workspace = true
actix-ws.workspace = true
chrono.workspace = true
futures-util.workspace = true
robine-api-contract = { path = "../robine-api-contract" }
robine-application = { path = "../robine-application" }
robine-domain = { path = "../robine-domain" }
robine-mcp-types = { path = "../robine-mcp-types" }
robine-matter-contract = { path = "../robine-matter-contract" }
robine-store-sqlite = { path = "../robine-store-sqlite" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
uuid.workspace = true
