[package]
name = "robine-matterd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
robine-matter-contract = { path = "../robine-matter-contract" }
robine-secret-store = { path = "../robine-secret-store" }
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
