[package]
name = "robine-integration-matter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
robine-application = { path = "../robine-application" }
robine-domain = { path = "../robine-domain" }
robine-matter-contract = { path = "../robine-matter-contract" }
thiserror.workspace = true

[dev-dependencies]
robine-store-sqlite = { path = "../robine-store-sqlite" }

