[package]
name = "robine-flow-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
robine-domain = { path = "../robine-domain" }
robine-flow-plan = { path = "../robine-flow-plan" }
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true
