[package]
name = "robine-protocol-mqtt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
robine-application = { path = "../robine-application" }
robine-domain = { path = "../robine-domain" }
robine-mqtt-contract = { path = "../robine-mqtt-contract" }
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
robine-store-sqlite = { path = "../robine-store-sqlite" }

