[package]
name = "robine-protocol-mqtt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
robine-application = { path = "../robine-application" }
robine-domain = { path = "../robine-domain" }
robine-mqtt-contract = { path = "../robine-mqtt-contract" }
robine-mqtt-compat-ha = { path = "../robine-mqtt-compat-ha" }
rumqttc.workspace = true
rustls.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
robine-store-sqlite = { path = "../robine-store-sqlite" }
